name: mubrm_tag
description: أول تطبيق يعمل بنظام NFC  في العراق
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.0
  shared_preferences: 0.5.7
  firebase_auth: ^0.18.1+2
  firebase_core : ^0.5.0
  firebase_storage: ^4.0.1
  firebase_messaging: ^7.0.3
  cloud_firestore: ^0.14.1+3
  image_picker: ^0.6.7+11
  provider: ^4.3.2+2
  flutter_modular: ^2.0.1
  uuid: ^2.0.2
  flutter_form_builder: ^3.14.0
  localstorage: ^3.0.0
  path_provider: ^1.6.21
  qr_flutter: ^3.2.0
  sqflite: ^1.3.1+1
  nfc_in_flutter: ^2.0.5
  reorderables: ^0.3.2
  url_launcher: ^5.7.6
  share: ^0.6.5+3
  intl: ^0.16.1
  google_sign_in: ^4.5.1
  nfc_manager: ^2.0.2

  flutter_localizations:
    sdk: flutter




dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.8.1


flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "images/PNG/icon.png"

#flutter pub run flutter_launcher_icons:main

flutter:

  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  assets:
     - images/PNG/
  fonts:
     - family: LBC
       fonts:
         - asset: fonts/LBC.ttf
flutter_intl:
  enabled: true
